const PhaseDetailsTypes = {
	DOMAIN_CATEGORY_STATE_CHANGE: 'DOMAIN_CATEGORY_STATE_CHANGE',
	ADD_PHASE_IN_PHASE_TABLE: 'ADD_PHASE_IN_PHASE_TABLE',
	UPDATE_PHASE_IN_PHASE_TABLE: 'UPDATE_PHASE_IN_PHASE_TABLE',
	REMOVE_PHASE_FROM_PHASE_TABLE: 'REMOVE_PHASE_FROM_PHASE_TABLE',
};

export default PhaseDetailsTypes;
